# Generated by Django 3.2.18 on 2023-03-22 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celery_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.CharField(max_length=128)),
                ('link', models.CharField(default=None, max_length=128)),
                ('lineFileLink', models.CharField(default=None, max_length=128)),
                ('size', models.CharField(default=None, max_length=32)),
                ('numberOfRoIs', models.CharField(default=None, max_length=32)),
                ('processTime', models.CharField(default=None, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=128)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow1.celery_task')),
            ],
        ),
        migrations.CreateModel(
            name='LayerAndROIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(max_length=128)),
                ('roi', models.CharField(max_length=128)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow1.images')),
            ],
        ),
    ]
